### PR TITLE
Port from GObject to GLib

### PR DESCRIPTION
**Pull request by aryanharitsh123**
I have done all the commits into one. the activity is working fine. Tested by Hrishi and me.

### CODE REVIEW

**Comment by anmol27katyani** [comment]
@pro-panda Please review

**Comment by quozl** [comment]
Reviewed.  Tested on Ubuntu 18.04 with Sugar 0.112.  Function is okay.  Fixes https://github.com/sugarlabs/across-and-down-activity/issues/4.

Code change doesn't follow upstream repository though, as I'd mentioned in #6 already, for good reasons, so my response is a Nak.

**Comment by aryanharitsh123** [comment]
Do you want me create a patch of the last commit? by using "git format-patch -1"?

**Comment by quozl** [comment]
Never mind, quicker to do it myself than explain.  Here's what I did;

```bash
$ cd sugargame
$ git format-patch -1
0001-Port-from-GObject-to-GLib.patch
$ cd ../across-and-down-activity
$ git am ../sugargame/0001-Port-from-GObject-to-GLib.patch
$ git push
```

Thanks for your help in identifying the changes.  You did good.

**Pull request closed without merging**
